rondo = [{ "text": "… die Bärge tüend sich büüge", "solution": "Steets in Truure" },
{ "text": ".. the jungle, the quiet jungle", "solution": "The lion sleeps tonight" },
{ "text": "Es ist die Eifersucht die mich …", "solution": "Alles aus liebe" },
{ "text": "… Labadab dab dab life", "solution": "Live is Liefe" },
{ "text": "… hör ich singen, und die Schatten …", "solution": "Altes haus" },
{ "text": "…Liebi chunt u Liebi geit", "solution": "Alperose" },
{ "text": "…da partigiano, tu mi devi seppelir", "solution": "O bella ciao" },
{ "text": "…si mola cosi…", "solution": "Quando si pianta la bella polenta" },
{ "text": "…She’s no time for talkin’ shes just…", "solution": "Streets of London" },
{ "text": "Wit äwäg vom Lärm vo der Stadt", "solution": "Louenesee" },
{ "text": "…auzain ils mauns!", "solution": "Contura Song" },
{ "text": "Hat’s Messer rausgezogen", "solution": "Bolle" },
{ "text": "..no wär worde drus…", "solution": "Zundhözli" },
{ "text": "..ganz versteckt schläft ganz wohlgemut…", "solution": "Seefahrt" },
{ "text": "…bis die Lichter nach …", "solution": "Über den Wolken" },
{ "text": "Ref. Mmmm Mmmm Mmmm (summen)", "solution": "S’Elli" },
{ "text": ", wo mich guet verstand", "solution": "S’Elli" },
{ "text": "Goûtons voir, oui, oui, oui", "solution": "Chevaliers de la table ronde" },
{ "text": "Hellai lilaililo", "solution": "Man stürzte sich zur Sonntagszeit" },
{ "text": "..das Erbsenmus mit Schweinekopf", "solution": "Man stürzte sich zur Sonntagszeit" },
{ "text": "Söili-Drache", "solution": "Sibe Chugelrundi Söi" },
{ "text": "Dörrgemüse", "solution": "Bolle" },
{ "text": ".. I’m dynamite (*), and I’ll win the fight", "solution": "TNT" },
{ "text": "Fidiri, fidira, fidirallala", "solution": "Es Buurebüebli" },
{ "text": "Am Abe, wo’sisch sächsi gsy", "solution": "EEs wott es Froueli" },
{ "text": "Dr Güggel het sis Ei verleit", "solution": "Es wott es Froueli" },
{ "text": "Chaschper, mir wie zämeha", "solution": "Es wott es Froueli" },
{ "text": "..auf dem alten Banjo..", "solution": "Jack ist in der Küche bei Tina" },
{ "text": "…il fiore del partigiano…", "solution": "O bella ciao" },
{ "text": "..täglich robotten…", "solution": "Hier kommt Alex" },
{ "text": "..de Roger isch am furze", "solution": "Heicho" },
{ "text": "…sone wilde Hippie mit gflickte Hosebei", "solution": "Kiosk" },
{ "text": "..Oder wie e Kasseschrank", "solution": "Kiosk" },
{ "text": "… het ne zwüsche d’Chralle gno", "solution": "Dr Eskimo" },
{ "text": " ..lai la lai, lai la lai, la lai la lai", "solution": "Boxer" },
{ "text": "… there, older than the trees", "solution": "Take me home" },
{ "text": "... take it slowly, you’re still young", "solution": "Father and Son" },
{ "text": "«Stop complaining», said the farmer", "solution": "Donna Donna" },
{ "text": "Mine ist he sunlight, mine is the morning", "solution": "Morning has broken" },
{ "text": "I said something wrong now", "solution": "Yesterday" },
{ "text": "U hocke irgendwo ab wo’s grad Platz het", "solution": "I schänke dir mis Härz" },
{ "text": "L’on z dans, sur le pont", "solution": "Sur le pont d’Avignon" },
{ "text": "I can’t use it anymore", "solution": "Knockin’ on heavens door" },
{ "text": "Oh ladz lend your hand! I cried", "solution": "Lady in black" },
{ "text": "De Felix seit yum Boxer Clay:", "solution": "De gröscht" },
{ "text": "Au solei sous la pluie", "solution": "Champs Elisees" },
{ "text": "Let me find my piece of heaven", "solution": "Heaven" },
{ "text": "Mit Seil und Haken..", "solution": "Wenn wir erklimmen" },
{ "text": "Whisper words of wisdom", "solution": "Let it be" },
{ "text": "Du dörfsch nöt gah", "solution": "Am Ufer vom Rhy" },
{ "text": "…das hett mi de no mängisch gstört", "solution": "Schwan" }]